"""created expiration attribute for Orderrs

Revision ID: 0d42baaf7528
Revises: 2544f0d072ff
Create Date: 2023-01-30 17:37:35.603465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d42baaf7528'
down_revision = '2544f0d072ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('expires', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'expires')
    # ### end Alembic commands ###
