"""created delivery date attribute for Orderrs

Revision ID: 31ec34cb0368
Revises: 0d42baaf7528
Create Date: 2023-01-30 17:52:48.383415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31ec34cb0368'
down_revision = '0d42baaf7528'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery')
    # ### end Alembic commands ###
