"""added new columns to cart and order items

Revision ID: 9f58738fc49a
Revises: 66c6bcd7d348
Create Date: 2023-01-27 08:45:32.065635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f58738fc49a'
down_revision = '66c6bcd7d348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('option', sa.String(), nullable=True))
    op.add_column('order_items', sa.Column('option', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'option')
    op.drop_column('cart_items', 'option')
    # ### end Alembic commands ###
